version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "America/New_York"
    labels:
      - "dependencies 🛠"

  - package-ecosystem: "npm" # See documentation for possible values.
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "America/New_York"
    labels:
      - "dependencies 🛠"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
      patch:
        update-types:
          - patch
      eslint:
        patterns:
          - '*eslint*'
      typescript:
        patterns:
          - '*typescript*'
          - '@types*'
      github:
        patterns:
          - '@actions*'
          - '@octokit*'
