  name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '* * * * *'

  Test-Action: # make sure the action works on a clean machine without building
    name: Test - Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          days-before-stale: 2